version: '3.8'

services:
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: XvrTnrtV!6^o@Qr2Ft&G#TkQ
      POSTGRES_USER: lgm_afk
    networks:
      - application
  lgm-backend:
    image: lgm-backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "6001:6001"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db
    networks:
      - application
  lgm-frontend:
    image: lgm-frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "6000:6000"
    depends_on:
      - lgm-backend
    networks:
      - application

networks:
  application:
    name: application
    driver: bridge
